title: MTN.fire
description: Testimony. Fire. Truth. From the mountains.
baseurl: "" # leave blank for custom domains like www.mtnfire.org
url: "https://www.mtnfire.org"
theme: minima

plugins:
  - jekyll-feed
